apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: analytics-mcp-backend
  namespace: agentgateway-system
spec:
  mcp:
    targets:
    - name: analytics-mcp-target
      static:
        host: analytics-mcp.streaming-backend.svc.cluster.local
        port: 8082
        protocol: StreamableHTTP
