service:
  type: ClusterIP
products:
  agentgateway:
    enabled: true
    namespace: agentgateway-system
  mesh:
    enabled: true
  kagent:
    enabled: false
  agentregistry:
    enabled: false
clickhouse:
  enabled: true
tracing:
  verbose: true
