# Remote peer: leaf-2 reaches leaf-1 (cluster2)
# address is injected by install script after east-west gateways are up
remote:
  create: true
  items:
    - name: istio-remote-peer-cluster2
      cluster: cluster2
      network: cluster2
      addressType: IPAddress
      address: "192.168.5.3"
      preferredDataplaneServiceType: loadbalancer
      trustDomain: cluster2.local
