apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ingress-to-chatbot
  namespace: wgu-demo-frontend
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - "*/ns/agentgateway-system/sa/ingress"
    to:
    - operation:
        ports: ["8501"]
