apiVersion: v1
kind: Namespace
metadata:
  name: wgu-demo
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: wgu-demo-waypoint
---
apiVersion: v1
kind: Namespace
metadata:
  name: wgu-demo-frontend
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: kagent
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: solo-enterprise
  labels:
    istio.io/dataplane-mode: ambient
